config/routes.rb
HelloStreaming::Application.routes.draw do
  get 'test' => 'test#index'
  get 'random' => 'test#random'

  get 'chat/index' => 'chat#index'
  post 'chat/create' => 'chat#create'
  get 'chat/events' => 'chat#events'

  root to: 'chat#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  include ActionController::Live

  def index
    @chats = Chat.all
  end

  def create
    response.headers["Content-Type"] = "text/javascript"
    @chat = Chat.create(name: params[:name], message: params[:message])
    $redis.publish('chat.create', @chat.to_json)
  end

  def events
    response.headers["Content-Type"] = "text/event-stream"
    redis = Redis.new
    redis.psubscribe('chat.*') do |on|
      on.pmessage do |pattern, event, data|
        response.stream.write("event: #{event}\n")
        response.stream.write("data: #{data}\n\n")
      end
    end
  rescue IOError
    logger.info "Stream closed"
  ensure
    redis.quit
    response.stream.close
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  include ActionController::Live

  def index
    10.times do |i|
      response.stream.write "#{i+1}.hello world<br />\n"
      sleep 1
    end
    response.stream.close
  end

  def random
    lang = ["Ruby", "Python", "Node.JS", "Java", "Scala", "PHP"]
    100.times do
      random = rand(lang.length).to_i
      response.stream.write "I love #{lang[random]}<br />\n"
      sleep random
    end
    response.stream.close
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/chat/create.js.erb
$('form#chat_form')[0].reset();

app/views/chat/index.html.erb
<h1>Live CHAT</h1>

<ul id="chat_room">
<% @chats.each do |c| %>
  <li><%= c.name %>: <%= c.message %></li>
<% end %>
</ul>

<%= form_tag chat_create_path, remote: true, id: :chat_form do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :message %>
  <%= text_field_tag :message %>
  <%= submit_tag 'Send' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloStreaming</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>